---
versions:
  ocp: 3.5
system:
  rpms:
    - createrepo
    - curl
    - vim
rpm_repositories:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.5-rpms
  - rhel-7-fast-datapath-rpms
registries:
  # utility/handy images usually for
  # use on the system that will be
  # the bastion system for installing
  - name: docker
    url: docker.io
    tag: latest
    push: false
    images:
      - registry
      - nginx
  # openshift images that will be rehosted
  # in the internal registry
  - name: ose3-component-images
    url: registry.access.redhat.com
    tag: v3.5
    images:
    - openshift3/ose-haproxy-router
    - openshift3/ose-deployer
    - openshift3/ose-sti-builder
    - openshift3/ose-docker-builder
    - openshift3/ose-pod
    - openshift3/ose-docker-registry
    - openshift3/ose-haproxy-router
    - openshift3/ose-deployer
    - openshift3/ose-sti-builder
    - openshift3/ose-docker-builder
    - openshift3/ose-pod
    - openshift3/ose-docker-registry
    - openshift3/logging-deployer
    - openshift3/logging-elasticsearch
    - openshift3/logging-kibana
    - openshift3/logging-fluentd
    - openshift3/logging-curator
    - openshift3/logging-auth-proxy
    - openshift3/metrics-deployer
    - openshift3/metrics-hawkular-metrics
    - openshift3/metrics-cassandra
    - openshift3/metrics-heapster
    - openshift3/registry-console
  # host, binary, and s2i images that will be rehosted in the
  # internal registry
  - name: ose3-hosted-images
    url: registry.access.redhat.com
    tag: latest
    images: []
